<?php
/**
 * @file
 * Create a button for page printing needs.
 */

/**
 * Implements hook_block_info().
 */
function ding_print_button_block_info() {
  $blocks = array();

  $blocks['print_button'] = array(
    'info' => t('Print button'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ding_print_button_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'print_button':
      $module_path = drupal_get_path('module', 'ding_print_button');
      drupal_add_js($module_path .'/js/ding_print_button.js', array('scope' => 'footer', 'weight' => 99));
      drupal_add_css($module_path .'/css/ding_print_button.css');

      // Block markup.
      $block['subject'] = t('Print button');
      $block['content'] = l(
        theme_image(array('path' => $module_path . '/img/icon-print.png', 'attributes' => array())) . t('Print'), '#',
        array(
          'attributes' => array(
            'class' => array(
              'print-button',
            ),
          ),
          'html' => TRUE,
        )
      );
      break;
  }

  return $block;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ding_print_button_preprocess_25_50_25(&$variables) {
  $user_bookmarks = arg(0) == 'list' && is_numeric(arg(1));

  $user_pages_array = array(
    'status-loans-overdue',
    'status-loans',
    'status-reservations-ready',
    'status-reservations',
    'my-library',
    'status-debts'
  );

  if (!$user_bookmarks && !in_array(arg(2), $user_pages_array)) {
    return;
  }

  $block = module_invoke('ding_print_button', 'block_view', 'print_button');
  $print_button_markup =
    '<div class="panel-pane pane-block pane-print-button">' .
    '<div class="pane-content">' .
    render($block['content']) .
    '</div>' .
    '</div>';

  $existing_content = $variables['content']['main_content'];
  $variables['content']['main_content'] = $print_button_markup . $existing_content;
}
